
import{auth,db}from"../firebase-config.js";import{doc,getDoc}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
const uid=localStorage.getItem("baladStaffUid");if(!uid)location.href="staff-login.html";document.getElementById("year").textContent=new Date().getFullYear();
function addTool(title,text,href){const e=document.createElement("div");e.className="tile";e.innerHTML='<strong>'+title+'</strong><p>'+text+'</p><a class="btn" href="'+href+'">Open</a>';document.getElementById("staffTools").appendChild(e)}
async function load(){try{const snap=await getDoc(doc(db,"staff",uid));if(!snap.exists())throw Error("Staff profile not found.");const p=snap.data(),role=String(p.role||"").toLowerCase(),classes=Array.isArray(p.assignedClasses)?p.assignedClasses:[],subjects=Array.isArray(p.assignedSubjects)?p.assignedSubjects:[],home=p.homeroom||p.classTeacherOf||"";if(p.active!==true||!["teacher","class_teacher","management","other"].includes(role))throw Error("Account is not authorized.");document.getElementById("welcome").textContent="Welcome, "+(p.name||p.loginCode||"Staff");document.getElementById("identity").textContent="Login code: "+(p.loginCode||"—");document.getElementById("role").textContent=role.toUpperCase();document.getElementById("classes").textContent=classes.join(", ")||"No teaching classes assigned";document.getElementById("subjects").textContent=subjects.join(", ")||"No teaching subjects assigned";document.getElementById("status").textContent="Active";
if(role==="class_teacher"&&home){addTool("My Class Management","Manage "+home+": create students, edit biodata and upload passport photos.","class-management.html");addTool("Class Result Review","Review the complete "+home+" class result.","../class-teacher-result-review.html");}
if((role==="teacher"||role==="class_teacher"||role==="management")&&subjects.length){addTool("Subject Result Entry","Enter results only for your assigned subjects and classes.","../subject-result-entry.html");}
addTool("Student Result Portal","View the school result portal.","../results.html");if(!document.getElementById("staffTools").children.length)document.getElementById("noTools").style.display="";
}catch(e){localStorage.clear();alert(e.message||"Unable to load staff profile.");location.href="staff-login.html"}}
document.getElementById("logout").onclick=async()=>{try{await signOut(auth)}finally{["baladStaffUid","baladStaffIdToken","baladStaffRole","baladStaffName","baladStaffLoginCode"].forEach(k=>localStorage.removeItem(k));location.href="staff-login.html"}};load();
